## Question 1:
### Create and transform vectors and matrices into transpose and conjugate transpose. 

In [2]:
import numpy as np
import pandas as pd
#CREATE A MATRIX
arr3=np.array([[8,14,-6],[12,7,4],[-11,3,2]])
print("MATRIX IS------------------------------\n\n",arr3,"\n\n")
#TRANSFORMED INTO TRANSPOSE MATRIX
print("TRANSPOSE OF MATRIX IS-----------------\n\n",arr3.transpose(),"\n\n")
#TRANSFORMED INTO CONJUGATE TRANSPOSE
arr4=np.array([[2+3j,1+1j],[4-7j,6+1j],[-3-2j,4+2j]])
print("MATRIX IS----------------------------\n\n",arr4,"\n\n")
cjarr4=arr4.conjugate()
print("CONJUGATE OF MATRIX IS---------------\n\n",cjarr4,"\n\n")
trarr4=cjarr4.transpose()
print("TRANSPOSE OF MATRIX IS---------------\n\n",trarr4,"\n\n")


MATRIX IS------------------------------

 [[  8  14  -6]
 [ 12   7   4]
 [-11   3   2]] 


TRANSPOSE OF MATRIX IS-----------------

 [[  8  12 -11]
 [ 14   7   3]
 [ -6   4   2]] 


MATRIX IS----------------------------

 [[ 2.+3.j  1.+1.j]
 [ 4.-7.j  6.+1.j]
 [-3.-2.j  4.+2.j]] 


CONJUGATE OF MATRIX IS---------------

 [[ 2.-3.j  1.-1.j]
 [ 4.+7.j  6.-1.j]
 [-3.+2.j  4.-2.j]] 


TRANSPOSE OF MATRIX IS---------------

 [[ 2.-3.j  4.+7.j -3.+2.j]
 [ 1.-1.j  6.-1.j  4.-2.j]] 




## Question 2:
### Generate the matrix into echelon form and find its rank.

In [3]:
#GENERATING A MATRIX
import sympy as sp
arr5=sp.Matrix([[4,0,1],[2,0,2],[3,0,3]])
print("MATRIX IS------------------\n\n",arr5,"\n\n")

#CONVERTING INTO REDUCED ROW ECHELON FORM
mrref=arr5.rref()
print("MATRIX IN REDUCED ROW ECHELON FORM IS------\n\n",mrref,"\n")

#RANK OF A MATRIX
rk=arr5.rank()
print("-------------------------------------------\n")
print("RANK OF THE MATRIX IS :",rk)


MATRIX IS------------------

 Matrix([[4, 0, 1], [2, 0, 2], [3, 0, 3]]) 


MATRIX IN REDUCED ROW ECHELON FORM IS------

 (Matrix([
[1, 0, 0],
[0, 0, 1],
[0, 0, 0]]), (0, 2)) 

-------------------------------------------

RANK OF THE MATRIX IS : 2


## Question 3:
### Find the determinant, cofactor,  adjoint , inverse, using numpy.

In [4]:
import numpy as np
def op_numpy(mat1):
    det1=np.linalg.det(mat1)
    if det1!=0:   
        inv1=np.linalg.inv(mat1)
        cof1=inv1.transpose()
        adj1=cof1.transpose()
    else:
        print("MATRIX IS SINGULAR")
    return (round(det1),inv1,cof1,adj1)
mat1=np.array([[1,2,3],[0,1,4],[5,6,0]])
print("MATRIX IS: \n\n", mat1,"\n\n")
D,I,C,A=op_numpy(mat1)
print("DETERMINANT OF MATRIX IS: \n\n", D,"\n\n")
print("COFACTOR OF MATRIX IS: \n\n", C, "\n\n")
print("ADJOINT OF MATRIX IS: \n\n", A, "\n\n")
print("INVERSE OF MATRIX IS: \n\n", I, "\n\n")

MATRIX IS: 

 [[1 2 3]
 [0 1 4]
 [5 6 0]] 


DETERMINANT OF MATRIX IS: 

 1 


COFACTOR OF MATRIX IS: 

 [[-24.  20.  -5.]
 [ 18. -15.   4.]
 [  5.  -4.   1.]] 


ADJOINT OF MATRIX IS: 

 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]] 


INVERSE OF MATRIX IS: 

 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]] 




### Find the determinant, cofactor,  adjoint , inverse, using sympy.

In [5]:
import sympy as sp
def op_sympy(mat2):
    det2=sp.det(mat2)
    if det2!=0:
        cof2=mat2.cofactor_matrix()
        adj2=mat2.adjugate()
        inv2=mat2.inverse_ADJ()
    else:
        print("MATRIX IS SINGULAR")
    return (det2,inv2,cof2,adj2)
mat2=sp.Matrix([[1,2,3],[0,1,4],[5,6,0]])
print("MATRIX IS : \n\n", mat2, "\n\n")
D,I,C,A=op_sympy(mat2)
print("DETERMINANT OF MATRIX IS: \n\n", D,"\n\n")
print("COFACTOR OF MATRIX IS: \n\n", C, "\n\n")
print("ADJOINT OF MATRIX IS: \n\n", A, "\n\n")
print("INVERSE OF MATRIX IS: \n\n", I, "\n\n")

MATRIX IS : 

 Matrix([[1, 2, 3], [0, 1, 4], [5, 6, 0]]) 


DETERMINANT OF MATRIX IS: 

 1 


COFACTOR OF MATRIX IS: 

 Matrix([[-24, 20, -5], [18, -15, 4], [5, -4, 1]]) 


ADJOINT OF MATRIX IS: 

 Matrix([[-24, 18, 5], [20, -15, -4], [-5, 4, 1]]) 


INVERSE OF MATRIX IS: 

 Matrix([[-24, 18, 5], [20, -15, -4], [-5, 4, 1]]) 




# Question 4:
### Solve a system of Homogenous and Non-Homogenous equations using Gauss Elimination method.

In [7]:
import numpy as np
import sys
n=int(input("ENTER THE NUMBER OF UNKNOWS:"))
print()
a=np.zeros((n,n+1))
x=np.zeros(n)
for i in range(n):
    for j in range(n+1):
        a[i][j] = int(input( 'a['+str(i)+']['+ str(j)+']='))
print("\n\n THE MATRIX IS: \n\n", a)
for i in range(n):
    if a[i][i]==0.0:
        sys.exit("DIVIDE BY ZERO DETECTED")
    for j in range(i+1,n):
        ratio=a[j][i]/a[i][i]
        for k in range(n+1):
            a[j][k]=a[j][k]-ratio*a[i][k]
x[n-1]=a[n-1][n]/a[n-1][n-1]
for i in range(n-2,-1,-1):
    x[i]=a[i][n]
    for j in range(i+1,n):
        x[i]=x[i]-a[i][j]*x[j]
    x[i]=x[i]/a[i][i]
print("REQUIRED SOLUTION IS:\n")
for i in range(n):
    print("X",i," = ",x[i],end="\t\t",sep="")

ENTER THE NUMBER OF UNKNOWS: 2


a[0][0]= 1
a[0][1]= 2
a[0][2]= 3
a[1][0]= 4
a[1][1]= 5
a[1][2]= 6




 THE MATRIX IS: 

 [[1. 2. 3.]
 [4. 5. 6.]]
REQUIRED SOLUTION IS:

X0 = -1.0		X1 = 2.0		

## Question 5:
### Solve a system of homogenous equations using Gauss jordan method.

In [17]:
import numpy as np
import sys

print("----------GAUSS JORDAN METHOD-----------")
n = int(input("ENTER THE NUMBER OF UNKNOWNS: "))
a = np.zeros((n, n + 1))
x = np.zeros(n)
for i in range(n):
    for j in range(n + 1):
        a[i][j] = float(input(f'a[{i}][{j}]= '))
print("\nAugmented Matrix Coefficients:")
print(a)
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit("\nError: Division by zero detected.")
    div = a[i][i]
    for j in range(n + 1):
        a[i][j] /= div
    for k in range(n):
        if k != i:
            ratio = a[k][i]
            for j in range(n + 1):
                a[k][j] -= ratio * a[i][j]
for i in range(n):
    x[i] = a[i][n]

print("\nRequired solution by Gauss-Jordan method:")
for i in range(n):
    print(f'x[{i}] = {x[i]:.4f}', end="\t")
print()


----------GAUSS JORDAN METHOD-----------


ENTER THE NUMBER OF UNKNOWNS:  2
a[0][0]=  1
a[0][1]=  2
a[0][2]=  3
a[1][0]=  4
a[1][1]=  5
a[1][2]=  6



Augmented Matrix Coefficients:
[[1. 2. 3.]
 [4. 5. 6.]]

Required solution by Gauss-Jordan method:
x[0] = -1.0000	x[1] = 2.0000	


## Question 6:
### Generate basis of column space, null space, row space and left null space of a matrix space.

In [18]:
from sympy import *  
M = Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]])
print("Matrix Used is : ")
print(M)
M_columnspace = M.columnspace()  
      
print("\nColumn Space of the Matrix is : ")
print(M_columnspace)

# Use sympy.rowspace() method 
M_rowspace = M.rowspace()
      
print("\nRow Space of the Matrix is : ")
print(M_rowspace)

# Use sympy.nullspace() method 
M_nullspace = M.nullspace()  
      
print("\nNull Space of the Matrix is : ")
print(M_nullspace)
# Use sympy.nullspace() method 
MT = M.T
M_leftnullspace = MT.nullspace()  
print("\nMatrix Transpose is : ")
print(MT)

print("\nLeft Null Space of the Matrix is : ")
print(M_leftnullspace)


Matrix Used is : 
Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]])

Column Space of the Matrix is : 
[Matrix([
[ 1],
[ 2],
[-1]]), Matrix([
[ 0],
[ 3],
[-3]])]

Row Space of the Matrix is : 
[Matrix([[1, 0, 1, 3]]), Matrix([[0, 3, 2, 1]])]

Null Space of the Matrix is : 
[Matrix([
[  -1],
[-2/3],
[   1],
[   0]]), Matrix([
[  -3],
[-1/3],
[   0],
[   1]])]

Matrix Transpose is : 
Matrix([[1, 2, -1], [0, 3, -3], [1, 4, -3], [3, 7, -4]])

Left Null Space of the Matrix is : 
[Matrix([
[-1],
[ 1],
[ 1]])]


## Question 7:
### Check the linear dependence of vectors. Generate a linear combination of given vectors of Rn matrices of the same size and find the transition matrix of given matrix space.

In [28]:
import numpy as np
matrix = np.array([[0, 1, 0, 0], 
                   [0, 0, 1, 0], 
                   [0, 1, 1, 0], 
                   [1, 0, 0, 1]])

print("The matrix is:\n", matrix)
print("Determinant of the given matrix:", np.linalg.det(matrix))
for i in range(matrix.shape[0]):    
    for j in range(matrix.shape[0]):
        if i != j:
            inner_product = np.inner(matrix[:, i], matrix[:, j])
            norm_i = np.linalg.norm(matrix[:, i])
            norm_j = np.linalg.norm(matrix[:, j])

            print("\nI:", matrix[:, i]) 
            print("J:", matrix[:, j])
            print("Inner Product:", inner_product)
            print("Norm i:", norm_i)
            print("Norm j:", norm_j)

            if np.abs(inner_product - norm_j * norm_i) < 1E-5:
                print("Dependent")
            else:
                print("Independent")

The matrix is:
 [[0 1 0 0]
 [0 0 1 0]
 [0 1 1 0]
 [1 0 0 1]]
Determinant of the given matrix: 0.0

I: [0 0 0 1]
J: [1 0 1 0]
Inner Product: 0
Norm i: 1.0
Norm j: 1.4142135623730951
Independent

I: [0 0 0 1]
J: [0 1 1 0]
Inner Product: 0
Norm i: 1.0
Norm j: 1.4142135623730951
Independent

I: [0 0 0 1]
J: [0 0 0 1]
Inner Product: 1
Norm i: 1.0
Norm j: 1.0
Dependent

I: [1 0 1 0]
J: [0 0 0 1]
Inner Product: 0
Norm i: 1.4142135623730951
Norm j: 1.0
Independent

I: [1 0 1 0]
J: [0 1 1 0]
Inner Product: 1
Norm i: 1.4142135623730951
Norm j: 1.4142135623730951
Independent

I: [1 0 1 0]
J: [0 0 0 1]
Inner Product: 0
Norm i: 1.4142135623730951
Norm j: 1.0
Independent

I: [0 1 1 0]
J: [0 0 0 1]
Inner Product: 0
Norm i: 1.4142135623730951
Norm j: 1.0
Independent

I: [0 1 1 0]
J: [1 0 1 0]
Inner Product: 1
Norm i: 1.4142135623730951
Norm j: 1.4142135623730951
Independent

I: [0 1 1 0]
J: [0 0 0 1]
Inner Product: 0
Norm i: 1.4142135623730951
Norm j: 1.0
Independent

I: [0 0 0 1]
J: [0 0 0 1]
Inner P

## Question 8:
### Find the orthonormal basis of a given vector space using the Gram-Schmidt orthogonalization process.

In [31]:
import numpy as np
def gram_schmidt(vectors):
    basis = []
    for v in vectors:
        w = v - np.sum( np.dot(v,b)*b  for b in basis )
        if (w > 1e-10).any():  
            basis.append(w/np.linalg.norm(w))
    return np.array(basis)
vectors = np.array(
    [[0, 0, 1],
     [0, 0, 1],
     [1, 1, 1]])
RS=gram_schmidt(vectors)
print("THE BASIS ARE:\n", RS)

THE BASIS ARE:
 [[0.         0.         1.        ]
 [0.70710678 0.70710678 0.        ]]


C:\Users\ss724\AppData\Local\Temp\ipykernel_6616\333762546.py:5: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  w = v - np.sum( np.dot(v,b)*b  for b in basis )


## Question 10:
### Application of Linear algebra: Coding and decoding of messages using nonsingular matrices.eg code "Linear Algebra is fun" and then decode it.

In [38]:
import numpy as np
from numpy.linalg import inv

# Encoding matrix
ecm = np.array([[3, 4], [3, 6]])

# Lists of Alphabets and their values
smallalpha = [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o",
              "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
capitalalpha = [" ", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N",
                "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
alphavalues = list(range(28))

# String to convert
b = "Linear Algebra is Fun"
listb = list(b)
lenb = len(listb)

# Convert word to numeric values for encoding
a = []
for char in listb:
    if char in smallalpha:
        a.append(alphavalues[smallalpha.index(char)])
    elif char in capitalalpha:
        a.append(alphavalues[capitalalpha.index(char)])

# Ensure length is even for matrix operations
if len(a) % 2 == 1:
    a.append(0)  # Padding with zero

# Convert list to 2D array for matrix multiplication
a = np.array(a).reshape(2, -1)

# Multiply by encoding matrix
c = np.matmul(ecm, a)

# Convert back to 1D array for display
encrypted_values = c.flatten().astype(int)

print("Encoding matrix:\n", ecm)
print("Encrypted form:", encrypted_values)

# Decoding process

# Convert encrypted array back to 2D matrix
tdm = encrypted_values.reshape(2, -1)

# Multiply by inverse matrix
dcm = np.matmul(inv(ecm), tdm)

# Convert back to 1D array for extracting text
decoded_values = np.round(dcm.flatten()).astype(int)

# Create the decoded word
decoded_text = ""
for num in decoded_values:
    if 0 <= num < len(smallalpha):  # Ensuring valid range
        decoded_text += smallalpha[num]

print("Decoded message:", decoded_text.strip())  # Removing padding spaces if any


Encoding matrix:
 [[3 4]
 [3 6]]
Encrypted form: [ 44  99  46  15  39 130   0  27 120  77  15  48 135  48  15  57 168   0
  39 162 105  15]
Decoded message: linear algebra is fun


## Question 11:
### Compute the gradient of a scalar field.

In [40]:
import numpy as np
print("GRADIENT OF A SCALAR FIELD")
m= np.array([1, 2, 4, 7, 11, 16], dtype=float)
print("\nInput    : ", m)
print("\nGradient : ", np.gradient(m))

GRADIENT OF A SCALAR FIELD

Input    :  [ 1.  2.  4.  7. 11. 16.]

Gradient :  [1.  1.5 2.5 3.5 4.5 5. ]


## Question 12:
### Compute Divergence of a vector field.

In [41]:
import numpy as np

def divergence(F):
    return np.ufunc.reduce(np.add,np.gradient(F))

print("DIVERGENCE OF A VECTOR FIELD")
m = np.array([1, 2, 4, 7, 11, 16], dtype=float)

print("\n Input      : ", m)

print("\n Divergence : ", divergence(m))


DIVERGENCE OF A VECTOR FIELD

 Input      :  [ 1.  2.  4.  7. 11. 16.]

 Divergence :  18.0


## Question 13:
### Compute curl of a vector field.

In [42]:
from sympy.physics.vector import ReferenceFrame
from sympy.physics.vector import curl
R = ReferenceFrame('R')

F = R[1]**2 * R[2] * R.x - R[0]*R[1] * R.y + R[2]**2 * R.z

print("CURL OF A VECTOR FEILD")

print("\nSuppose F(x,y,z) = (y^2)zi - xyj + z2k, then:")
print("-> x would be R[0], y would be R[1] and z would be R[2]")
print("-> The unit vectors i, j, k of the 3 axes, would be respectively R.x, R.y, R.z")

print("\nVector is    : ", F)

CURL = curl(F, R)  
print("\nCurl will be : ", CURL)

print("\n-> In other words, CURL = 0i + (y^2)j + (-2yz-y)k")


CURL OF A VECTOR FEILD

Suppose F(x,y,z) = (y^2)zi - xyj + z2k, then:
-> x would be R[0], y would be R[1] and z would be R[2]
-> The unit vectors i, j, k of the 3 axes, would be respectively R.x, R.y, R.z

Vector is    :  R_y**2*R_z*R.x - R_x*R_y*R.y + R_z**2*R.z

Curl will be :  R_y**2*R.y + (-2*R_y*R_z - R_y)*R.z

-> In other words, CURL = 0i + (y^2)j + (-2yz-y)k
